### ISSUE TITLE
Fix 'This overload and the one on line 22 can be combined into one signature with an optional parameter.' issue in src\secure-rm.ts

### ISSUE THREAD

**Issue by ghost** [secure-rm/core#11]
[CodeFactor](https://www.codefactor.io/repository/github/secure-rm/core) found an issue: This overload and the one on line 22 can be combined into one signature with an optional parameter.

It's currently on:
[src\secure-rm.ts:23
](https://www.codefactor.io/repository/github/secure-rm/core/source/master/src/secure-rm.ts#L23)

https://app.leanboard.io/board/46b3ca48-4a30-4014-899a-53be4943c92f

**Comment by SteelAlloy** [comment]
Fixed with  #v4.0.0
